steps:
  # Install dependencies
  - name: node
    entrypoint: yarn
    args: ["install"]
  # Test Codebase
  - name: node
    entrypoint: yarn
    args: ["test:run"]
  # Build project
  - name: node
    entrypoint: yarn
    args: ["build"]
  # Deploy to Firebase Hosting
  - name: gcr.io/kiranbansode-resume/firebase
    args: ["hosting:channel:deploy", "testing", "--project=kiranbansode-resume"]
