steps:
  # Install dependencies
  - name: node
    entrypoint: yarn
    args: ["install"]
  # Build project
  - name: node
    entrypoint: yarn
    args: ["build"]
  # Deploy to Firebase Hosting
  - name: gcr.io/kiranbansode-resume/firebase
    args: ["deploy", "--project=kiranbansode-resume", "--only=hosting"]
